apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-goals
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-goals
subjects:
  - kind: ServiceAccount
    name: default
    namespace: security-goals
