steps:
  - name: node:11.10-alpine
    dir: performance-index
    entrypoint: npm
    args: ['install']
  - name: node:11.10-alpine
    dir: performance-index
    entrypoint: npm
    args: ['test']
    env:
    - 'CI=true'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'performance-index'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/performance-index:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/performance-index:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment/performance-index
    - performance-index=gcr.io/$PROJECT_ID/performance-index:$SHORT_SHA
    - --namespace=security-goals
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=security-goals'
images:
  - 'gcr.io/$PROJECT_ID/performance-index:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/performance-index:latest'