steps:
  - name: node:11.10-alpine
    dir: performance-index
    entrypoint: npm
    args: ['install']
  - name: node:11.10-alpine
    dir: performance-index
    entrypoint: npm
    args: ['test']
    env:
    - 'CI=true'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'performance-index'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/performance-index:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/performance-index:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/performance-index:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/performance-index:latest'