apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: compliance-ui 
  name:  compliance-ui
  namespace: symmorfosi
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: compliance-ui 
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: compliance-ui
    spec:
      containers:
        - image: cdssnc/compliance-ui
          imagePullPolicy: Always
          name: compliance-ui 
          env:
            - name: PORT
              value: '3000'
            - name: API_URL
              value: 'http://compliance-api:3000'
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
