apiVersion: v1
kind: Service
metadata:
  labels:
    name: compliance-ui
  name: compliance-ui
  namespace: symmorfosi
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: compliance-ui

