apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-23T16:02:35Z
  generation: 1
  labels:
    run: compliance-api
  name: compliance-api
  namespace: default
  resourceVersion: "4861"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/compliance-api
  uid: 0e657a41-d6dd-11e8-a07d-90576b471f22
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: compliance-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: compliance-api
    spec:
      containers:
      - image: cdssnc/compliance-api
        imagePullPolicy: Always
        name: compliance-api
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: compliance-checks
          mountPath: /checks
      initContainers:
      - image: cdssnc/check-sa-11-1
        imagePullPolicy: Always
        name: compliance-check-sa-11-1
        env:
        - name: URL
          value: https://github.com/cds-snc/platform-challenge
        volumeMounts:
        - name: compliance-checks
          mountPath: /checks
      volumes:
      - name: compliance-checks
        hostPath:
          path: /checks
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-23T16:02:45Z
    lastUpdateTime: 2018-10-23T16:02:45Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-10-23T16:02:35Z
    lastUpdateTime: 2018-10-23T16:02:45Z
    message: ReplicaSet "compliance-api-78c86dfb58" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
