steps:
  - name: node:11.10-alpine
    dir: notifier
    entrypoint: yarn
    args: ['install']
  - name: node:11.10-alpine
    dir: notifier
    entrypoint: yarn
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'notifier'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/notifier:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/notifier:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment/notifier
    - notifier=gcr.io/$PROJECT_ID/notifier:$SHORT_SHA
    - --namespace=security-goals
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=security-goals'
images:
  - 'gcr.io/$PROJECT_ID/notifier:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/notifier:latest'