steps:
  - name: node:11.10-alpine
    dir: web-report
    entrypoint: npm
    args: ['install']
  - name: node:11.10-alpine
    dir: web-report
    entrypoint: npm
    args: ['test']
    env:
    - 'CI=true'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'web-report'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/web-report:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/web-report:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/web-report:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/web-report:latest'