steps:
  - name: node:11.10-alpine
    dir: web-report
    entrypoint: npm
    args: ['install']
  - name: node:11.10-alpine
    dir: web-report
    entrypoint: npm
    args: ['test']
    env:
    - 'CI=true'
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'web-report'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/web-report:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/web-report:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment/web-report
    - web-report=gcr.io/$PROJECT_ID/web-report:$SHORT_SHA
    - --namespace=security-goals
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=security-goals'
images:
  - 'gcr.io/$PROJECT_ID/web-report:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/web-report:latest'