steps:
  - name: node:11.10-alpine
    dir: pdf-report
    entrypoint: yarn
    args: ['install']
  - name: node:11.10-alpine
    dir: pdf-report
    entrypoint: yarn
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'pdf-report'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/pdf-report:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/pdf-report:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/pdf-report:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/pdf-report:latest'