apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-au-6
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-au-6'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The organization does audit reports and reviews in line with written policy.'
            - name: SATISFIES
              value: 'AU-6'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/audit-review.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
