apiVersion: batch/v1
kind: Job
metadata:
  name: pod-check-compliance-au-8-fluentd
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-au-8-fluentd'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Fluentd for logging.'
            - name: SATISFIES
              value: 'AU-8,AU-8 (1),SI-11'
            - name: NEEDLE
              value: 'fluentd'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
