apiVersion: batch/v1
kind: Job
metadata:
  name: pod-check-compliance-ca-2
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-kube-hunter'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Kube hunter for vulnerability scanning.'
            - name: SATISFIES
              value: 'CA-2 (2),RA-5,SA-11,SA-15 (4)'
            - name: NEEDLE
              value: 'kube-hunter'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
