apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-cm-2
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-cm-2'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses kubernetes configuration files to manage its state and information inventory in source control with a log of changes by users.'
            - name: SATISFIES
              value: 'CM-2,CM-6 (1),CM-8,CM-8 (1),CM-8 (4)'
            - name: URL
              value: 'https://raw.githubusercontent.com/cds-snc/mrpinchy-confession-box/master/manifests/base/kustomization.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
