apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-cm-7
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-cm-7'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses pod security policies to restrict ports and user priviliges.'
            - name: SATISFIES
              value: 'CM-7'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/manifests/base/pod-security-policy.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
