apiVersion: batch/v1
kind: Job
metadata:
  name: pod-check-compliance-sa-12-kritis
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/pod-check-compliance:latest'
          imagePullPolicy: Always
          name: 'pod-check-compliance-sa-12-kritis'
          env:
            - name: ORIGIN
              value: 'cdssnc/pod-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The cluster uses Kritis to block deployment of vulnerable container images.'
            - name: SATISFIES
              value: 'SA-12'
            - name: NEEDLE
              value: 'kritis'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
