apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-sa-11-1
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-sa-11-1'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses an ESLint file to do so static code analysis.'
            - name: SATISFIES
              value: 'SA-11,SA-11 (1)'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/.eslintrc.json'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
