apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-sc-12
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-sc-12'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application uses symmetric keys to use secrets in the build pipeline.'
            - name: SATISFIES
              value: 'SC-12,SC-13'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/cloudbuild.yaml'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
