apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-si-10
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-si-10'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Source code'
            - name: DESCRIPTION
              value: 'The application contains tests to validate inputs and error logging.'
            - name: SATISFIES
              value: 'SA-11,SI-10,SI-11'
            - name: URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box/blob/master/__tests__/form.test.js'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
