apiVersion: batch/v1
kind: Job
metadata:
  name: url-check-compliance-si-17
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-si-17'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application implements the fail-safe policy.'
            - name: SATISFIES
              value: 'SI-17'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/fail-safe.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
