apiVersion: batch/v1
kind: Job
metadata:
  name: github-issues-check-compliance-si-2
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/github-issues-check-compliance:latest'
          imagePullPolicy: Always
          name: 'github-issues-check-compliance-si-2'
          env:
            - name: ORIGIN
              value: 'cdssnc/github-issues-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'This application uses GitHub issues for flaw remediation.'
            - name: SATISFIES
              value: 'SA-11,SA-22,SI-2'
            - name: REPO_URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
