apiVersion: batch/v1
kind: Job
metadata:
  name: github-snyk-check-compliance-si-5
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/github-snyk-check-compliance:latest'
          imagePullPolicy: Always
          name: 'github-snyk-check-compliance-si-5'
          env:
            - name: ORIGIN
              value: 'cdssnc/github-snyk-check-compliance:latest'
            - name: COMPONENT
              value: 'Infrastructure'
            - name: DESCRIPTION
              value: 'The application uses snyk to detect package vulnerabilities.'
            - name: SATISFIES
              value: 'SA-11,SI-5'
            - name: REPO_URL
              value: 'https://github.com/cds-snc/mrpinchy-confession-box'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
