apiVersion: batch/v1
kind: Job
metadata:
  name: 'url-check-compliance-pl-8' 
  namespace: symmorfosi
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - image: 'cdssnc/url-check-compliance:latest'
          imagePullPolicy: Always
          name: 'url-check-compliance-pl-8'
          env:
            - name: ORIGIN
              value: 'cdssnc/url-check-compliance:latest'
            - name: COMPONENT
              value: 'Policy'
            - name: DESCRIPTION
              value: 'The application follows the guidelines laid out in the Information Architecture guide.'
            - name: SATISFIES
              value: 'PL-8'
            - name: URL
              value: 'https://github.com/cds-snc/compliance-policy-documents/information-architecture.md'
          volumeMounts:
            - name: compliance-checks
              mountPath: /checks
      volumes:
        - name: compliance-checks
          persistentVolumeClaim:
            claimName: checks-claim
