steps:
  - name: node:11.10-alpine
    dir: runner
    entrypoint: npm
    args: ['install']
  - name: node:11.10-alpine
    dir: runner
    entrypoint: npm
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'runner'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/runner:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/runner:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/runner:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/runner:latest'