steps:
  - name: 'node:alpine'
    dir: 'api'
    entrypoint: 'yarn'
    args: ['install']
  - name: "node:alpine"
    dir: 'api'
    entrypoint: 'yarn'
    args: ['test']
    env:
     - 'CHECKS_PATH=src/__tests__/testData/checks'
     - 'DEFINITIONS_URL=https://raw.githubusercontent.com/cds-snc/ITSG-33-definitions/master/ITSG-33a.yaml'
     - 'DB_URI=mongodb://'
     - 'DB_USER='
     - 'DB_PASS='
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'api'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/api:$SHORT_SHA',
        '-t',
        'gcr.io/$PROJECT_ID/api:latest',
        '-f',
        'Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
    - set
    - image
    - deployment/api
    - api=gcr.io/$PROJECT_ID/api:$SHORT_SHA
    - --namespace=security-goals
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=security-goals'
images:
  - 'gcr.io/$PROJECT_ID/api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/api:latest'